### ISSUE TITLE
Correción PC2 (error ortográfico)

### ISSUE THREAD

**Issue by DayaneRojas1506** [cs1000-utec/pc2#1]
![image](https://user-images.githubusercontent.com/91268793/145485161-70dcd53a-3ff8-4dbd-b211-dc604f046e4c.png)
Profesor como podrá ver aquí el error está en la palabra "opcion". 
La palabra corregida sería : opción.
Motivo: PC1

**Comment by franciscovilchezv** [comment]
Proceder
